# Generated by Django 4.2.9 on 2024-01-15 11:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_authuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='18ce892a66a770dd91a4c2e2e002722771b8f78fa7e81f02904941d19706b64e', max_length=64, null=True)),
                ('expires_at', models.DateTimeField(default=datetime.datetime(2024, 1, 15, 12, 17, 53, 84849, tzinfo=datetime.timezone.utc))),
                ('activated_at', models.DateTimeField(default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
